// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCHoeOhooTAYuZ2fDpEP5gRxUJt5MGO-7Y",
    authDomain: "mobileapp-2c37c.firebaseapp.com",
    projectId: "mobileapp-2c37c",
    storageBucket: "mobileapp-2c37c.firebasestorage.app",
    messagingSenderId: "195245441057",
    appId: "1:195245441057:web:29f04ca1d7002a3887e360",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCHoeOhooTAYuZ2fDpEP5gRxUJt5MGO-7Y",
    authDomain: "mobileapp-2c37c.firebaseapp.com",
    projectId: "mobileapp-2c37c",
    storageBucket: "mobileapp-2c37c.firebasestorage.app",
    messagingSenderId: "195245441057",
    appId: "1:195245441057:web:29f04ca1d7002a3887e360",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCHoeOhooTAYuZ2fDpEP5gRxUJt5MGO-7Y",
    authDomain: "mobileapp-2c37c.firebaseapp.com",
    projectId: "mobileapp-2c37c",
    storageBucket: "mobileapp-2c37c.firebasestorage.app",
    messagingSenderId: "195245441057",
    appId: "1:195245441057:web:29f04ca1d7002a3887e360",
  );
}
